"""
Revision ID: 'ee2c5d44776b'
Revises: None
Create Date: datetime.datetime(2026, 10, 4, 13, 20, 12, 576785)
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "ee2c5d44776b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("CREATE SCHEMA IF NOT EXISTS conversation"))
    op.execute(sa.text("CREATE SCHEMA IF NOT EXISTS evaluation"))
    op.execute(sa.text("CREATE SCHEMA IF NOT EXISTS lead"))
    op.execute(sa.text("CREATE SCHEMA IF NOT EXISTS platform"))
    op.execute(sa.text("CREATE SCHEMA IF NOT EXISTS workflow"))
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(length=32), server_default="CREATED", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.CheckConstraint(
            "state IN ("
            "'CREATED', 'CONNECTING', 'GREETING', 'DISCOVERY', 'QUALIFICATION', "
            "'SCORING', 'DECISION', 'FOLLOW_UP', 'HUMAN_HANDOFF', 'COMPLETED', 'FAILED'"
            ")",
            name=op.f("ck_conversations_conversation_state_values"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        schema="conversation",
    )
    op.create_table(
        "scenarios",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scenario_key", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scenarios")),
        sa.UniqueConstraint("scenario_key", name=op.f("uq_scenarios_scenario_key")),
        schema="evaluation",
    )
    op.create_table(
        "leads",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("synthetic_profile_key", sa.String(length=120), nullable=False),
        sa.Column("intent", sa.String(length=160), nullable=True),
        sa.Column("target_country", sa.String(length=80), nullable=True),
        sa.Column("preferred_language", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="NEW", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leads")),
        sa.UniqueConstraint("synthetic_profile_key", name=op.f("uq_leads_synthetic_profile_key")),
        schema="lead",
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("actor", sa.String(length=120), nullable=False),
        sa.Column("resource", sa.String(length=120), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
        schema="platform",
    )
    op.create_table(
        "domain_events",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=160), nullable=False),
        sa.Column("event_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("producer", sa.String(length=120), nullable=False),
        sa.Column("aggregate_type", sa.String(length=80), nullable=False),
        sa.Column("aggregate_id", sa.UUID(), nullable=False),
        sa.Column("aggregate_version", sa.Integer(), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=True),
        sa.Column("causation_id", sa.UUID(), nullable=True),
        sa.Column("request_id", sa.String(length=120), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.Column("idempotency_key", sa.String(length=160), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "occurred_at", sa.DateTime(timezone=True), server_default="now()", nullable=False
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("publish_attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_domain_events")),
        sa.UniqueConstraint(
            "aggregate_type", "aggregate_id", "aggregate_version", name="uq_event_aggregate_version"
        ),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_domain_events_idempotency_key")),
        schema="platform",
    )
    op.create_table(
        "fault_injections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=True),
        sa.Column("capability", sa.String(length=32), nullable=True),
        sa.Column("operation", sa.String(length=80), nullable=True),
        sa.Column("behavior", sa.String(length=32), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fault_injections")),
        schema="platform",
    )
    op.create_table(
        "processed_events",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("consumer_group", sa.String(length=120), nullable=False),
        sa.Column(
            "processed_at", sa.DateTime(timezone=True), server_default="now()", nullable=False
        ),
        sa.PrimaryKeyConstraint("event_id", "consumer_group", name=op.f("pk_processed_events")),
        schema="platform",
    )
    op.create_table(
        "provider_health",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("capability", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="UNKNOWN", nullable=False),
        sa.Column("circuit_state", sa.String(length=16), server_default="CLOSED", nullable=False),
        sa.Column("success_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("failure_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "error_rate", sa.Numeric(precision=7, scale=6), server_default="0", nullable=False
        ),
        sa.Column("latency_p50_ms", sa.Integer(), nullable=True),
        sa.Column("latency_p95_ms", sa.Integer(), nullable=True),
        sa.Column("last_failure", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failover_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_health")),
        sa.UniqueConstraint("provider", "capability", name="uq_provider_capability"),
        schema="platform",
    )
    op.create_table(
        "followups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="SCHEDULED", nullable=False),
        sa.Column("attempt", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="3", nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.CheckConstraint("attempt >= 0", name=op.f("ck_followups_followup_attempt_nonnegative")),
        sa.CheckConstraint(
            "max_attempts > 0", name=op.f("ck_followups_followup_max_attempts_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_followups")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_followups_idempotency_key")),
        schema="workflow",
    )
    op.create_table(
        "handoffs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("priority", sa.String(length=16), server_default="NORMAL", nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="REQUESTED", nullable=False),
        sa.Column(
            "requested_at", sa.DateTime(timezone=True), server_default="now()", nullable=False
        ),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_handoffs")),
        schema="workflow",
    )
    op.create_table(
        "calls",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("transport", sa.String(length=32), server_default="WEBRTC", nullable=False),
        sa.Column("status", sa.String(length=32), server_default="CREATED", nullable=False),
        sa.Column("runtime_instance_id", sa.String(length=120), nullable=True),
        sa.Column("connected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("disconnect_reason", sa.String(length=160), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.CheckConstraint(
            "status IN ('CREATED', 'CONNECTING', 'CONNECTED', 'RECONNECTING', 'ENDED', 'FAILED')",
            name=op.f("ck_calls_call_status_values"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversation.conversations.id"],
            name=op.f("fk_calls_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calls")),
        schema="conversation",
    )
    op.create_table(
        "conversation_summaries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("intent", sa.String(length=160), nullable=True),
        sa.Column(
            "concerns", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("next_action", sa.String(length=80), nullable=True),
        sa.Column(
            "qualification_changes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("generated_by", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversation.conversations.id"],
            name=op.f("fk_conversation_summaries_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversation_summaries")),
        sa.UniqueConstraint(
            "conversation_id", name=op.f("uq_conversation_summaries_conversation_id")
        ),
        schema="conversation",
    )
    op.create_table(
        "evaluation_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scenario_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="PENDING", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=True),
        sa.Column(
            "failure_reasons",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["evaluation.scenarios.id"],
            name=op.f("fk_evaluation_runs_scenario_id_scenarios"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_runs")),
        schema="evaluation",
    )
    op.create_table(
        "lead_score_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("previous_score", sa.Integer(), nullable=True),
        sa.Column("new_score", sa.Integer(), nullable=False),
        sa.Column("classification", sa.String(length=16), nullable=False),
        sa.Column(
            "reasons", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("rule_version", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.CheckConstraint(
            "new_score BETWEEN 0 AND 100",
            name=op.f("ck_lead_score_history_score_history_new_range"),
        ),
        sa.CheckConstraint(
            "previous_score IS NULL OR previous_score BETWEEN 0 AND 100",
            name=op.f("ck_lead_score_history_score_history_previous_range"),
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["lead.leads.id"],
            name=op.f("fk_lead_score_history_lead_id_leads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead_score_history")),
        schema="lead",
    )
    op.create_table(
        "lead_scores",
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.Integer(), server_default="0", nullable=False),
        sa.Column("classification", sa.String(length=16), server_default="COLD", nullable=False),
        sa.Column("rule_version", sa.String(length=32), nullable=False),
        sa.Column(
            "calculated_at", sa.DateTime(timezone=True), server_default="now()", nullable=False
        ),
        sa.CheckConstraint("score BETWEEN 0 AND 100", name=op.f("ck_lead_scores_lead_score_range")),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["lead.leads.id"],
            name=op.f("fk_lead_scores_lead_id_leads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("lead_id", name=op.f("pk_lead_scores")),
        schema="lead",
    )
    op.create_table(
        "qualification_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="INCOMPLETE", nullable=False),
        sa.Column("completeness", sa.Integer(), server_default="0", nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.CheckConstraint(
            "completeness BETWEEN 0 AND 100",
            name=op.f("ck_qualification_profiles_qualification_completeness_range"),
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["lead.leads.id"],
            name=op.f("fk_qualification_profiles_lead_id_leads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_qualification_profiles")),
        sa.UniqueConstraint("lead_id", name=op.f("uq_qualification_profiles_lead_id")),
        schema="lead",
    )
    op.create_table(
        "followup_attempts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("followup_id", sa.UUID(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="RUNNING", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "result", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["followup_id"],
            ["workflow.followups.id"],
            name=op.f("fk_followup_attempts_followup_id_followups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_followup_attempts")),
        sa.UniqueConstraint("followup_id", "attempt_number", name="uq_followup_attempt_number"),
        schema="workflow",
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("call_id", sa.UUID(), nullable=True),
        sa.Column("speaker", sa.String(length=16), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.CheckConstraint(
            "speaker IN ('USER', 'AGENT', 'SYSTEM', 'TOOL')",
            name=op.f("ck_messages_message_speaker_values"),
        ),
        sa.ForeignKeyConstraint(
            ["call_id"],
            ["conversation.calls.id"],
            name=op.f("fk_messages_call_id_calls"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversation.conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint(
            "conversation_id", "sequence_number", name="uq_message_conversation_sequence"
        ),
        schema="conversation",
    )
    op.create_table(
        "transcript_segments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("call_id", sa.UUID(), nullable=True),
        sa.Column("speaker", sa.String(length=16), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("segment_type", sa.String(length=32), server_default="FINAL", nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("is_final", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("provider_segment_id", sa.String(length=160), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.CheckConstraint(
            "speaker IN ('USER', 'AGENT', 'SYSTEM', 'TOOL')",
            name=op.f("ck_transcript_segments_transcript_speaker_values"),
        ),
        sa.ForeignKeyConstraint(
            ["call_id"],
            ["conversation.calls.id"],
            name=op.f("fk_transcript_segments_call_id_calls"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversation.conversations.id"],
            name=op.f("fk_transcript_segments_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transcript_segments")),
        sa.UniqueConstraint(
            "conversation_id", "provider_segment_id", name="uq_transcript_provider_segment"
        ),
        sa.UniqueConstraint(
            "conversation_id", "sequence_number", name="uq_transcript_conversation_sequence"
        ),
        schema="conversation",
    )
    op.create_table(
        "evaluation_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("evaluation_run_id", sa.UUID(), nullable=False),
        sa.Column("assertion_key", sa.String(length=160), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("expected", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actual", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.ForeignKeyConstraint(
            ["evaluation_run_id"],
            ["evaluation.evaluation_runs.id"],
            name=op.f("fk_evaluation_results_evaluation_run_id_evaluation_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_results")),
        sa.UniqueConstraint("evaluation_run_id", "assertion_key", name="uq_evaluation_assertion"),
        schema="evaluation",
    )
    op.create_table(
        "qualification_answers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("qualification_profile_id", sa.UUID(), nullable=False),
        sa.Column("field_key", sa.String(length=80), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("normalized_value", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column(
            "answer_status", sa.String(length=32), server_default="PROVISIONAL", nullable=False
        ),
        sa.Column("source", sa.String(length=32), server_default="AGENT", nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name=op.f("ck_qualification_answers_answer_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["qualification_profile_id"],
            ["lead.qualification_profiles.id"],
            name=op.f("fk_qualification_answers_qualification_profile_id_qualification_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_qualification_answers")),
        sa.UniqueConstraint(
            "qualification_profile_id", "field_key", name="uq_qualification_answer_field"
        ),
        schema="lead",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("qualification_answers", schema="lead")
    op.drop_table("evaluation_results", schema="evaluation")
    op.drop_table("transcript_segments", schema="conversation")
    op.drop_table("messages", schema="conversation")
    op.drop_table("followup_attempts", schema="workflow")
    op.drop_table("qualification_profiles", schema="lead")
    op.drop_table("lead_scores", schema="lead")
    op.drop_table("lead_score_history", schema="lead")
    op.drop_table("evaluation_runs", schema="evaluation")
    op.drop_table("conversation_summaries", schema="conversation")
    op.drop_table("calls", schema="conversation")
    op.drop_table("handoffs", schema="workflow")
    op.drop_table("followups", schema="workflow")
    op.drop_table("provider_health", schema="platform")
    op.drop_table("processed_events", schema="platform")
    op.drop_table("fault_injections", schema="platform")
    op.drop_table("domain_events", schema="platform")
    op.drop_table("audit_log", schema="platform")
    op.drop_table("leads", schema="lead")
    op.drop_table("scenarios", schema="evaluation")
    op.drop_table("conversations", schema="conversation")
    op.execute(sa.text("DROP SCHEMA IF EXISTS workflow"))
    op.execute(sa.text("DROP SCHEMA IF EXISTS platform"))
    op.execute(sa.text("DROP SCHEMA IF EXISTS lead"))
    op.execute(sa.text("DROP SCHEMA IF EXISTS evaluation"))
    op.execute(sa.text("DROP SCHEMA IF EXISTS conversation"))
    # ### end Alembic commands ###
